const configStory = [
  {
    idx: 0,
    distance: 0,
    autokm: 0,
    interventions: 0,
    xAutoText: 1,
    xManualText: 2.5,
    xInterventionText: 2,
    isVehicleSectionHidden: true,
    chapter: 1,
    title: "Kilometers per Intervention (km/I)",
    text: "This is a key metric we track to show how far our vehicles are able to travel before an intervention happens. Let’s dive into how we calculate this.",
  },
  {
    idx: 1,
    distance: 0,
    autokm: 0,
    interventions: 0,
    xAutoText: 1,
    xManualText: 2.5,
    xInterventionText: 2,
    chapter: 2,
    title: "Two Modes of Operation",
    text: "Our vehicles currently have two basic modes: autonomy and manual. Autonomy is when the vehicle drives itself. Manual is when a driver takes control of the vehicle.",
  },
  {
    idx: 2,
    distance: 1,
    autokm: 1,
    interventions: 0,
    xAutoText: 1,
    xManualText: 2.5,
    xInterventionText: 2,
    chapter: 3,
    title: "Calculating km/I",
    text: "The km/I formula is affected by how far the vehicle travels in autonomy mode and the number of interventions.",
  },
  {
    idx: 3,
    distance: 2,
    autokm: 2,
    interventions: 1,
    xAutoText: 1,
    xManualText: 2.5,
    xInterventionText: 2,
    interventionOpacity: 1,
    chapter: 4,
    title: "What is an Intervention?",
    text: "An intervention occurs any time we drop out of autonomy mode into manual mode.",
  },
  {
    idx: 4,
    distance: 3,
    autokm: 2,
    interventions: 1,
    xAutoText: 3.5,
    xManualText: 2.5,
    xInterventionText: 2,
    chapter: 5,
    title: "Manual Mode",
    text: "When we drive in manual mode, we don’t count the manual driven distance in our km/I formula.",
  },
  {
    idx: 5,
    distance: 4,
    autokm: 3,
    interventions: 2,
    xAutoText: 3.5,
    xManualText: 4.5,
    xInterventionText: 4,
    interventionOpacity: 1,
    chapter: 6,
    title: "Longest Autonomous Distance",
    text: "So far, we are able to travel 1.5 km (on average) before an intervention occurs.",
  },
  {
    idx: 6,
    distance: 5,
    autokm: 3,
    interventions: 2,
    xAutoText: 8.5,
    manualText: " ",
    xManualText: 2.5,
    xInterventionText: 4,
    interventionReasonsOpacity: 1,
    chapter: 7,
    title: "Why Interventions Occur?",
    text: "One reason for an intervention is when the vehicle enters a manual only zone that is dictated by our Operational Design Domain (ODD). It’s a fancy way of saying situations the current autonomy system is not designed to handle. For example, we do not currently allow our autonomy system to make unprotected left turns. It requires a manual only zone when we enter the intersection.",
  },
  {
    idx: 7,
    distance: 8,
    autokm: 3,
    interventions: 2,
    xAutoText: 8.5,
    xManualText: 9.5,
    xInterventionText: 4,
    interventionReasonsOpacity: 1,
    chapter: 8,
    title: "Other Intervention Reasons",
    text: "Weather and construction are other reasons we see an intervention. But the most common reason for an intervention is that the Autonomous Vehicle Operator (AVO) took over of their own accord.",
  },
  {
    idx: 8,
    distance: 9,
    autokm: 4,
    interventions: 2,
    xAutoText: 8.5,
    xManualText: 9.5,
    interventionText: "RARE intervention",
    xInterventionText: 9,
    interventionOpacity: 1,
    chapter: 9,
    title: "Two types of Interventions",
    text: "We have two main types of interventions: RARE (Re-Sim At-Fault Reportable Events) and non-RARE. We replay events leading up to the intervention in our simulator to see what would have happened if we did not enter manual mode. A RARE intervention means that the simulator showed that the intervention was needed because our system was not designed to handle it. A non-RARE intervention means that the intervention was not necessary.",
  },
  {
    idx: 9,
    distance: 10,
    autokm: 4,
    interventions: 3,
    xAutoText: 8.5,
    xManualText: 9.5,
    interventionText: "RARE intervention",
    xInterventionText: 9,
    interventionOpacity: 1,
    chapter: 10,
    title: "Our Performance Numbers",
    text: "View our current metrics below for both RARE and non-RARE interventions at our sites.",
  },
];
export default configStory;
